-- Check if DMFs exist
SHOW USER FUNCTIONS LIKE 'DMF_RAW%' IN SCHEMA INSURANCECO.GOVERNANCE;

-- If they exist, grant usage to the table owner role
GRANT USAGE ON FUNCTION INSURANCECO.GOVERNANCE.DMF_RAW_INVALID_CLAIM_AMOUNT(TABLE(NUMBER)) TO ROLE <table_owner_role>;
-- Repeat for other DMFs...

-- Then resume each DMF

use role data_engineer;
use database insuranceco;
use schema raw;
ALTER TABLE INSURANCECO.RAW.RAW_CLAIMS 
  MODIFY DATA METRIC FUNCTION INSURANCECO.GOVERNANCE.DMF_RAW_INVALID_CLAIM_AMOUNT ON (CLAIM_AMOUNT) RESUME;


  ALTER TABLE INSURANCECO.RAW.RAW_CLAIMS 
  MODIFY DATA METRIC FUNCTION INSURANCECO.GOVERNANCE.DMF_RAW_INVALID_CLAIM_AMOUNT ON (CLAIM_AMOUNT)
    ADD EXPECTATION lessThan5Mins (VALUE < 300), lessThan30Mins (VALUE < 1800);

    SELECT table_name, metric_name, value, measurement_time
FROM SNOWFLAKE.LOCAL.DATA_QUALITY_MONITORING_RESULTS
WHERE table_database = 'INSURANCECO' 
  AND table_schema = 'RAW'
  AND metric_name LIKE 'DMF_RAW%'
ORDER BY measurement_time DESC
LIMIT 10;

    delete from  raw_claims;
    delete from  raw_policies;

    use schema curated;
    show tables;

        delete from  dim_claims;
    delete from  dim_policies;

        use schema analytics;
    show tables;

    delete from AGG_CLAIMS_EXECUTIVE;

            use schema data_science;
    show tables;
    delete from FRAUD_DETECTION_FEATURES;

    -- Grant execute privilege
GRANT EXECUTE DATA METRIC FUNCTION ON ACCOUNT TO ROLE DATA_ENGINEER;

-- Grant usage on each custom DMF
GRANT USAGE ON FUNCTION INSURANCECO.GOVERNANCE.DMF_RAW_INVALID_CLAIM_AMOUNT(TABLE(NUMBER)) TO ROLE DATA_ENGINEER;
GRANT USAGE ON FUNCTION INSURANCECO.GOVERNANCE.DMF_RAW_INVALID_DATES(TABLE(DATE, DATE)) TO ROLE DATA_ENGINEER;
GRANT USAGE ON FUNCTION INSURANCECO.GOVERNANCE.DMF_RAW_INVALID_EMAIL(TABLE(VARCHAR)) TO ROLE DATA_ENGINEER;
GRANT USAGE ON FUNCTION INSURANCECO.GOVERNANCE.DMF_RAW_INVALID_CPR(TABLE(VARCHAR)) TO ROLE DATA_ENGINEER;
GRANT USAGE ON FUNCTION INSURANCECO.GOVERNANCE.DMF_RAW_ORPHAN_CLAIMS(TABLE(VARCHAR), TABLE(VARCHAR)) TO ROLE DATA_ENGINEER;