-- Check if DMFs exist
SHOW USER FUNCTIONS LIKE 'DMF_RAW%' IN SCHEMA INSURANCECO.GOVERNANCE;

-- If they exist, grant usage to the table owner role
GRANT USAGE ON FUNCTION INSURANCECO.GOVERNANCE.DMF_RAW_INVALID_CLAIM_AMOUNT(TABLE(NUMBER)) TO ROLE <table_owner_role>;
-- Repeat for other DMFs...

-- Then resume each DMF
ALTER TABLE INSURANCECO.RAW.RAW_CLAIMS 
  MODIFY DATA METRIC FUNCTION INSURANCECO.GOVERNANCE.DMF_RAW_INVALID_CLAIM_AMOUNT ON (CLAIM_AMOUNT) RESUME;